"""empty message

Revision ID: 1104603ceced
Revises: None
Create Date: 2013-09-25 13:21:49.242000

"""

# revision identifiers, used by Alembic.
revision = '1104603ceced'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('first_post', sa.DateTime(), nullable=True),
    sa.Column('last_post', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=15), nullable=True),
    sa.Column('last_useragent', sa.String(length=200), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('banexpiration', sa.DateTime(), nullable=True),
    sa.Column('banreason', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=5000), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_ip', sa.String(length=15), nullable=True),
    sa.Column('image', sa.String(length=260), nullable=True),
    sa.Column('thumb', sa.String(length=260), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('randid', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('answer_to', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('answers', sa.Integer(), nullable=True),
    sa.Column('last_answer', sa.DateTime(), nullable=True),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('post')
    op.drop_table('user')
    ### end Alembic commands ###
