"""empty message

Revision ID: 4784d119c815
Revises: 1104603ceced
Create Date: 2013-09-25 23:04:22.854000

"""

# revision identifiers, used by Alembic.
revision = '4784d119c815'
down_revision = '1104603ceced'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fingerprint', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fingerprint')
    ### end Alembic commands ###
